server:
  port: 8080

spring:
  application:
    name: order-service

  kafka:
    bootstrap-servers: localhost:9092

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true